### ISSUE TITLE
Local build error: Landing page missing a title: index

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#155] opened 2021-03-05 00:49 UTC
While running `make book` locally, all of the content processing works fine, but the build process crashes with the following error. Any suggestions? 

```
Theme error:
An error happened in rendering the page README.
Reason: ValueError('Landing page missing a title: index')
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1022, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 192, in render
    return self.environment.get_template(template).render(context)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/layout.html", line 7, in top-level template code
    {%- set sidebar_width_class = "col-md-3" %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/../pydata_sphinx_theme/layout.html", line 10, in top-level template code
    <a class='right-next' id="next-link" href="{{ next.link|e }}" title="{{ _('next page')}}">{{ next_title or next.title }}</a>
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/themes/basic/../basic/layout.html", line 174, in top-level template code
    {%- block content %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/../pydata_sphinx_theme/layout.html", line 47, in block "content"
    {% block docs_sidebar %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/layout.html", line 30, in block "docs_sidebar"
    {% include "sidebar.html" %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/sidebar.html", line 14, in top-level template code
    {%- include sidebartemplate %}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/_templates/sbt-sidebar-nav.html", line 2, in top-level template code
    {{ generate_nav_html(include_item_names=True, with_home_page=theme_home_page_in_toc) }}
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx_book_theme/__init__.py", line 130, in generate_nav_html
    raise ValueError(f"Landing page missing a title: {master_doc}")
ValueError: Landing page missing a title: index

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 544, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 603, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1029, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page README.
Reason: ValueError('Landing page missing a title: index')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/d8/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 304, in build
    builder_specific_actions(
  File "/usr/local/anaconda3/envs/d8/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 546, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================

make: *** [book] Error 1
(d8)
```

**Comment by choldgraf** [comment] 2021-03-05 03:10
I think that this is a result of #156 so I'm going to close this as that issue is the real root cause of the problem

**Closed by choldgraf** 2021-03-05 03:10 UTC
